import { PrismaClient, FriendshipStatus } from '@prisma/client';
import { createAdminUser, createTestUsers, createRandomUsers } from './seed-data/users';
import { createPosts, createSamplePosts } from './seed-data/posts';
import { createReactions, createComments, createCommentReactions } from './seed-data/interactions';
import { createConversations, createSampleConversation } from './seed-data/messages';

const prisma = new PrismaClient();

interface SeedOptions {
  adminOnly?: boolean;
  full?: boolean;
  force?: boolean;
}

function parseArgs(): SeedOptions {
  const args = process.argv.slice(2);
  return {
    adminOnly: args.includes('--admin-only'),
    full: args.includes('--full'),
    force: args.includes('--force'),
  };
}

async function checkExistingData(): Promise<boolean> {
  const userCount = await prisma.user.count();
  return userCount > 0;
}

async function seedAdminOnly() {
  console.log('🌱 Seeding admin account only...');

  const admin = await createAdminUser(prisma);
  console.log('✅ Admin user created: admin@mega.dev');

  return { users: [admin], posts: [], comments: [] };
}

async function seedSampleData() {
  console.log('🌱 Seeding sample data...');

  // Create admin and test users
  console.log('👥 Creating users...');
  const admin = await createAdminUser(prisma);
  const testUsers = await createTestUsers(prisma, 5);
  const allUsers = [admin, ...testUsers];

  console.log(`  ✅ Created admin + ${testUsers.length} test users`);

  // Create friendships
  console.log('🤝 Creating friendships...');
  const friendshipCount = await createFriendships(prisma, testUsers);
  console.log(`  ✅ Created ${friendshipCount} friendships`);

  // Create sample posts
  console.log('📝 Creating posts...');
  const posts = await createSamplePosts(prisma, testUsers);
  console.log(`  ✅ Created ${posts.length} posts`);

  // Create interactions
  console.log('💬 Creating interactions...');
  const reactions = await createReactions(prisma, allUsers, posts, 0.4);
  const comments = await createComments(prisma, allUsers, posts, 0.3);
  console.log(`  ✅ Created ${reactions.length} reactions and ${comments.length} comments`);

  // Create sample conversations
  console.log('💌 Creating messages...');
  if (testUsers.length >= 2) {
    await createSampleConversation(prisma, testUsers[0], testUsers[1]);
    console.log('  ✅ Created sample conversation');
  }

  return { users: allUsers, posts, comments };
}

async function seedFullData() {
  console.log('🌱 Seeding full demo dataset...');

  // Create admin, test users, and random users
  console.log('👥 Creating users...');
  const admin = await createAdminUser(prisma);
  const testUsers = await createTestUsers(prisma, 5);
  const randomUsers = await createRandomUsers(prisma, 15);
  const allUsers = [admin, ...testUsers, ...randomUsers];

  console.log(`  ✅ Created ${allUsers.length} total users`);

  // Create comprehensive friendships
  console.log('🤝 Creating friendship network...');
  const friendshipCount = await createFriendshipNetwork(prisma, allUsers);
  console.log(`  ✅ Created ${friendshipCount} friendships`);

  // Create many posts
  console.log('📝 Creating posts...');
  const samplePosts = await createSamplePosts(prisma, testUsers);
  const randomPosts = await createPosts(prisma, randomUsers, 2);
  const allPosts = [...samplePosts, ...randomPosts];
  console.log(`  ✅ Created ${allPosts.length} posts with images`);

  // Create rich interactions
  console.log('💬 Creating interactions...');
  const reactions = await createReactions(prisma, allUsers, allPosts, 0.5);
  const comments = await createComments(prisma, allUsers, allPosts, 0.4);
  const commentReactions = await createCommentReactions(prisma, allUsers, comments, 0.2);
  console.log(`  ✅ Created ${reactions.length} post reactions, ${comments.length} comments, ${commentReactions.length} comment reactions`);

  // Create conversations
  console.log('💌 Creating conversations...');
  const conversations = await createConversations(prisma, allUsers, 10);
  console.log(`  ✅ Created ${conversations.length} conversations with messages`);

  // Create notifications (they would be auto-generated by the app in real usage)
  console.log('🔔 Note: Notifications will be generated automatically when users interact');

  return { users: allUsers, posts: allPosts, comments };
}

async function createFriendships(prisma: PrismaClient, users: any[]) {
  let count = 0;

  if (users.length >= 4) {
    // Create some accepted friendships
    await prisma.friendship.upsert({
      where: { requesterId_addresseeId: { requesterId: users[0].id, addresseeId: users[1].id } },
      update: {},
      create: {
        requesterId: users[0].id,
        addresseeId: users[1].id,
        status: FriendshipStatus.ACCEPTED,
      },
    });
    count++;

    await prisma.friendship.upsert({
      where: { requesterId_addresseeId: { requesterId: users[0].id, addresseeId: users[2].id } },
      update: {},
      create: {
        requesterId: users[0].id,
        addresseeId: users[2].id,
        status: FriendshipStatus.ACCEPTED,
      },
    });
    count++;

    // Create a pending request
    await prisma.friendship.upsert({
      where: { requesterId_addresseeId: { requesterId: users[3].id, addresseeId: users[0].id } },
      update: {},
      create: {
        requesterId: users[3].id,
        addresseeId: users[0].id,
        status: FriendshipStatus.PENDING,
      },
    });
    count++;
  }

  return count;
}

async function createFriendshipNetwork(prisma: PrismaClient, users: any[]) {
  let count = 0;

  // Create a realistic social network
  for (let i = 0; i < users.length; i++) {
    // Each user has 2-8 friends
    const friendCount = Math.min(
      Math.floor(Math.random() * 7) + 2,
      users.length - 1
    );

    const potentialFriends = users.filter(u => u.id !== users[i].id);
    const selectedFriends = potentialFriends
      .sort(() => Math.random() - 0.5)
      .slice(0, friendCount);

    for (const friend of selectedFriends) {
      try {
        // Check if friendship already exists in either direction
        const existing = await prisma.friendship.findFirst({
          where: {
            OR: [
              { requesterId: users[i].id, addresseeId: friend.id },
              { requesterId: friend.id, addresseeId: users[i].id },
            ],
          },
        });

        if (!existing) {
          await prisma.friendship.create({
            data: {
              requesterId: users[i].id,
              addresseeId: friend.id,
              status: Math.random() < 0.9
                ? FriendshipStatus.ACCEPTED
                : FriendshipStatus.PENDING,
            },
          });
          count++;
        }
      } catch (error) {
        // Skip on unique constraint violation
      }
    }
  }

  return count;
}

async function main() {
  const options = parseArgs();

  console.log('========================================');
  console.log('🚀 Mega Facebook Database Seeder');
  console.log('========================================');

  // Check for existing data
  const hasExistingData = await checkExistingData();

  if (hasExistingData && !options.force) {
    console.log('⚠️  Database already contains data.');
    console.log('   Use --force to re-run seeding anyway.');
    return;
  }

  if (options.force && hasExistingData) {
    console.log('⚠️  Force mode: Adding data to existing database...');
  }

  try {
    // Run in transaction for data consistency
    await prisma.$transaction(async (tx) => {
      let result;

      if (options.adminOnly) {
        result = await seedAdminOnly();
      } else if (options.full) {
        result = await seedFullData();
      } else {
        // Default: sample data
        result = await seedSampleData();
      }

      console.log('\n========================================');
      console.log('✅ Seeding completed successfully!');
      console.log('========================================');
      console.log('\n📊 Summary:');
      console.log(`  • Users: ${result.users.length}`);
      console.log(`  • Posts: ${result.posts.length}`);
      console.log(`  • Comments: ${result.comments.length}`);

      if (result.users.length > 0) {
        console.log('\n🔑 Test Accounts:');
        console.log('  • admin@mega.dev / Admin123!');
        if (!options.adminOnly) {
          console.log('  • user1@mega.dev / Test1234!');
          console.log('  • user2@mega.dev / Test1234!');
          console.log('  • (and more...)');
        }
      }
    }, {
      timeout: 60000, // 60 second timeout
    });
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

main()
  .catch((error) => {
    console.error('❌ Fatal error:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });