version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mega_postgres_test
    environment:
      POSTGRES_USER: mega
      POSTGRES_PASSWORD: mega_secret
      POSTGRES_DB: mega_facebook_test
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U mega -d mega_facebook_test']
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mega_redis_test
    ports:
      - '6380:6379'
    tmpfs:
      - /data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 3s
      retries: 5
